nestrilabs/nestri

.github/workflows/autolabeller.yml, .github/workflows/relay.yml, relay.Dockerfile
We are adding the `Dockerfile` to build a moq-relay
1. Added `relay.Dockerfile` with all the docker code to build kixelated's moq-relay.
2. Added `relay.yml` in workflows for building and publishing the docker image
=> ✨ feat: Add relay docker image

.github/labeler.yml, .github/labels.yml
=> 🔧 chore(github): Add labels for `ffmpeg` and `recorder`

.scripts/entrypoint.sh, server.Dockerfile
=> 🐛 fix(server): Add CAP_SYS* capabilities to the gpu-screen-recorder

.github/workflows/warp.yml, .gitmodules
`Warp` will be used to "trasmit" the video and audio from the container to the user/viewer wherever they are.
1. Add a Github worker that builds warp on pr, and one that builds and pushes on release
=> ✨ feat: Add warp (moq-pub)

.github/workflows/server.yml, .github/workflows/warp.yml, server.Dockerfile, warp.Dockerfile
Build times for netris:server are way too long. so the idea is to move warp into it's own container then build from there.
Later on first release we might drop this for a better solution.
1. Added the very own netris:warp
=> ✨ feat: Add a separate image to build warp

server.Dockerfile
=> ✨ feat(server): Copy warp from docker

.dev/script.sh, .dev/x11.sh, .scripts/entrypoint.sh, server.Dockerfile
=> ✨ feat: Capture screen and send with warp

.github/dependabot.yml, apps/www/src/routes/layout.tsx
Update the moq-server submodule to support audio
=> 🔧 chore: Use dependabot to maintain and update `moq-server`

server.Dockerfile
=> ✨ feat(server): Install winetricks

.scripts/supervisord.conf, server.Dockerfile
We need to remove the inputtino server, and replace it with `warp-input` server, which is developed in-house and it works.
=> ✨ feat(server): Add warp-input server

.scripts/entrypoint.sh, .scripts/proton, .scripts/supervisord.conf, server.Dockerfile
This is a catch all PR that tries to smooth out the creases found while playing using Netris.
What i have found so far:
1. Change `NAME` environment to `SESSION_ID` for warp server.
2. Run `entrypoint.sh` and `warp-input` as user `netris`
3. Netris-proton is broken, it quits prematurely. I think it has to be a problem with a missing wine installation
=> 🐛 fix(server): Final touches

README.md
Update the README to show how to how to run Netris.
=> 📝 docs(readme): Add manual setup and game launch instructions

.scripts/startup.sh
fix startup.sh by ryan himself
=> 🐛 fix(server): Remove `xargs` from startup.sh

.github/workflows/autolabeller.yml
Well, we figured out the first part(PR TITLE) and forgot about the labelling part. 😅 Consult #87 for more info
=> 🐛 fix(autolabeller): Use GITHUB_TOKEN for adding labels too

.gitmodules
We are adding an option to start the Nestri server (omg almost called it Netris :) using a cli
The idea is to reduce the friction of starting up the service and running it, this includes:
1. Installing and configuring the Windows executables for the game
2. Running the game on a linux machine
3. Preparing the host system i.e configuring Docker, Nvidia {Drivers,CUDA} etc etc
=> ✨ feat: Add nestri cli

apps/docs/components/content/Contributors.vue, apps/docs/content/0.index.md, apps/docs/content/1.introduction/1.what-is-nestri.md, apps/docs/content/1.introduction/2.faq.md, apps/docs/content/2.nestri-node/2.prerequisite.md, apps/docs/content/2.nestri-node/5.container-cli.md, apps/docs/content/2.nestri-node/5.gstreamer.md, apps/docs/nuxt.config.ts, apps/docs/package.json, package-lock.json
Added GitHub contributors to the homepage and and added the the Container CLI section with @DatCaptainHorse .
=> ✨feat: Updated Documentation

Cargo.lock, Containerfile.cachyos, packages/server/Cargo.toml, packages/server/src/main.rs
I've finished cooking :spaghetti:
=>  ✨ feat: Pipewire

apps/www/src/routes/play/[id]/index.tsx, packages/input/src/keyboard.ts, packages/server/src/main.rs
- Adds heartbeat to keep WS alive on nestri-server side
- Fixes inputs getting stuck on repeated keys, while also allowing modifiers to be sent after.
- For now treat Home keys as Esc to make games escapable.
- Add button to start stream, to fix browser preventing play issue.
=> 🐛fix: some input fixes, missing heartbeat

Cargo.lock, packages/server/Cargo.toml, packages/server/src/main.rs
Makes it run, I'll fix the race condition issues once we merge feat/rooms into feat/stream, otherwise, good work :+1:
=> fix: Add rustls ring provider for webrtc

.github/workflows/relay.yml, .github/workflows/runner.yml, containers/runner.Containerfile
This adds `nestri:relay` CI job  to the `feat/ci` base branch
=> ✨ feat: Run CI job for `nestri:relay`

apps/docs/content/2.nestri-node/2.prerequisite.md, apps/docs/content/2.nestri-node/6.node-faq.md
Updated the Nestri Node documentation regarding node requirements and added FAQ.
=> Updated the Nestri Node documentation

containers/runner.Containerfile
Nothing much- This just adds Steam to the image
=> ⭐ feat(runner): Add steam

containers/runner.Containerfile
This lets us do game backups with this command
`STEAMAPPID=730 ludusavi wrap --infer steam --force "steam://yourcommandhere"`
=> ⭐ feat(runner): Add ludusavi backups

packages/scripts/entrypoint.sh, packages/scripts/entrypoint_nestri.sh
=> ⭐ feat(scripts): Auto-launch Steam

.github/workflows/runner.yml, containers/runner.Containerfile
Not a draft PR despite being WIP as I need the CI to run
=> 🐜 fix(CI): Caching fixes and improvements

containers/runner.Containerfile
=> 🐜 fix(runner): Add missing source copy for gst-wayland-display

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
This tries to clear up the chaos on who is in charge of what
=> 🧹 chore: Add CODEOWNERS

containers/runner.Containerfile, packages/scripts/entrypoint_nestri.sh, packages/server/src/args/device_args.rs, packages/server/src/args/encoding_args.rs, packages/server/src/enc_helper.rs, packages/server/src/gpu.rs, packages/server/src/main.rs
Also includes other improvements and hopefully reducing LOC with some cleanup.
=> ⭐ feat(runner): DMA-BUF support (for NVIDIA)

packages/input/src/mouse.ts, packages/input/src/webrtc-stream.ts
Mouse Movements are aggreagated to send out with an fixed interval 16ms to fit 60fps
none
There is still the need of having a non fixed interval to adjust according to the framerate
none
This reduces sending mouse movement events especially when the mouse is moved really fast. The mouse events are not lost they will be summed and aggregated to one single mouse movement and then send with the fixed interval
=> ⭐ feat: Aggregated mouse movements

containers/runner.Containerfile, packages/scripts/entrypoint.sh, packages/scripts/entrypoint_nestri.sh, packages/scripts/envs.sh
This PR will be fixing issue of runner not working under Ubuntu and other Debian-based distros with NVIDIA GPUs.
Another fix will be arriving is allowing Steam to run without namespace requirements, removing the need for `--privileged` flag in certain situations.
=> 🐜 fix(runner): Workarounds for NVIDIA drivers

infra/bus.ts, infra/database.ts, infra/www.ts, packages/www/src/pages/new.tsx
Migrates to a neon account shared by the Nestrilabs organisation
=> 🐜 fix(db): Migrate to Neon org account

bun.lock, package.json, packages/www/src/App.tsx, packages/www/src/pages/new.tsx, packages/www/src/ui/form.tsx
=> 🧹 chore(www): Update the onboarding

bun.lock, packages/core/package.json, packages/functions/package.json, packages/www/package.json, packages/www/src/App.tsx, packages/www/src/ui/form.tsx
This fixes an issue where `openauthjs` throws timeout errors while attempting to access DynamoDB
> I am so glad this was not a major issue 😅
[OpenAuth Error TypeError: fetch failed while accessing DynamoDB on AWS #5543
](https://github.com/sst/sst/issues/5543)
[Error TypeError: fetch failed while accessing DynamoDB on AWS #220](https://github.com/toolbeam/openauth/issues/220)
=> 🐜 fix: Fix dynamodb errors when trying to authenticate

.github/workflows/www.yml
This attempts to deploy `apps/www` to the new CF account using cloudflare pages project
=> ⭐ feat(ci): Deploy nestri landing page

.github/workflows/www.yml
=> 🏇 ci(www): Test whether it is working

.github/workflows/www.yml
Fix an issue where the `apps/www` CI does not push to main
=> 🐜 fix(ci): Fix issue where main does not deploy to prod

.github/workflows/docs.yml, apps/docs/package.json
This deploys docs to cloudflare pages
=> 🏇🏾ci(docs): Deploy docs to cloudflare

infra/auth.ts, infra/bus.ts, infra/email.ts, infra/postgres.ts, infra/vpc.ts, packages/core/drizzle.config.ts, packages/core/src/drizzle/index.ts, packages/functions/sst-env.d.ts, sst-env.d.ts, sst.config.ts
The scope of this PR is to add a shared VPC for everyone on the team.
=> ⭐feat(infra): Use a shared VPC

.github/PULL_REQUEST_TEMPLATE.md
=> 🧹 chore: Use simpler PR template

apps/www/src/routes/(public)/index.tsx, apps/www/src/routes/(public)/pricing/index.tsx
Change the CTA for the landing page
=> 🐜 fix(www): Change CTA for now
