.github/workflows/server.yml
.scripts/proton
server.Dockerfile

We are adding the `Dockerfile` with all the scripts and programs to run our games in.
1. Add `serverDockerfile` which contains all the docker code.
2. Add `.scripts` folder where we will store all the scripts; for example in our case, where proton installation script will reside.

✨ feat: Add server Dockerfile

---

.github/workflows/server.yml
.scripts/gpu

Add a way to configure the Nvidia GPU, by installing the necessary packages for Proton to work.
We made a script `.scripts/gpu` when called like `gpu -c` it will install Vulkan and proprietry nvidia drivers.

✨ feat(server): Add Nvidia gpu configuration script

---

server.Dockerfile

Currently on `docker run --gpus 1 netris:server` and run `nvidia-smi` you get an error.
We add the relevant NVIDIA_* env variables to allow for gpu passthrough.

✨ feat(server): Add nvidia gpu passthrough support

---

.dev/x11.sh
server.Dockerfile
test.Dockerfile

We have no display server inside the container, nor Vulkan which will later be required by dxvk/d3d11/d3d12 in order to play games using Proton.
1. We added vulkan and Xwayland packages into `server.Dockerfile` , then tested with running `vkcube` and `vulkaninfo` after running an interactive bash shell inside the container.

✨ feat(server): Add Vulkan and Xwayland support

---

server.Dockerfile

We are adding mangohud (to show GPU usage), gamemode (for optimisations) and gamescope (as our compositor)
1. Apt install mangohud
2. Install gamescope from flatpak
3. And then build gamemode

✨ feat(server): Add mangohud, gamescope and gamemode

---

.github/workflows/recorder.yml
recorder.Dockerfile
server.Dockerfile

So, we have our simple compositor (`gamescope`), now we need a way to capture audio and video. 
And i have found this "performant" **_citation needed_ ** and minimal screen recorder, which has the capability to even capture 30 second screen snippets. 
1. Add a minimal step inside the DockerFile to build and install the gpu-screen-recorder

✨ feat(server): Add gpu-screen-recorder

---

server.Dockerfile

We succesfully built the gpu-screen-recorder in a separate container... now we need to add it into the main container
1. Copy the relevant user/bin files from the separate docker image
2.

✨ feat(server): Integrate gpu-screen-recorder into the server

---

.scripts/supervisord.conf
server.Dockerfile

Docker build server fails because `supervisord.conf` is getting copied to a different directory other than `/etc`

🐛 fix(server): Clean up the supervisord.conf and COPY supervisord.conf to /etc

---

.github/labeler.yml

There seems to be a problem with auto-labeler labelling `type:docs`. So i am adding to check on the `docs/**` branch too and label that accordingly.

🐛 fix(git): Add `docs/**` branch

---

.github/workflows/base.yml
.github/workflows/warp-input.yml
.github/workflows/warp.yml

`warp-input.yml` workflow was not getting invoked on push. So, I change the `Github Token` which has broader permissions.

🐛 fix(git): Release `warp*` docker images too

---

bin/input/src/main.rs

I am having issues trying to append `input` to the session_id using bash. Most probably because supervisord is using the ENV variables already available in the container. So, here we append the `input` part inside the rust binary instead. This is much cleaner and it works.

🐛 fix(input): Append `input` to server's session ID for now

---

.github/workflows/warp-input.yml

There is a bug whereby `netris/warp-input` does not build and deploy a new nightly docker image when a pr is merged. This happens when there are changes in `bin/input/**` directory, and this is not the expected behaviour. So i added the directory back into the `warp-input.yml` workflow file.

🐛 fix(git): Build warp-input on push to main

---

.scripts/entrypoint.sh
server.Dockerfile

With help from @djpremier, rename `/usr/bin/netris/proton` as "the script cannot be found in bash `(eg.: $ proton -r /games/AlanWake.exe)` if it is in the subdirectory of /usr/bin, probably because it is found in a subdir inside `/usr/bin` "

✨ feat(server): Rename `/netris/proton` to `netris-proton`

---

.scripts/entrypoint.sh

Currently, the container fails when trying to download drivers for a container running non-proprietary Nvidia drivers. So, this is a fix which searches for numbers rather than a fixed point in the string.

🐛 fix(server): Support the `Open Kernel Module`

---

bin/input/Cargo.toml
bin/input/src/cli.rs
bin/input/src/input.rs
bin/input/src/main.rs

`Warp-input` server errors out when the namespace or `session_id` has not yet been created on our relay. 
This is a problem, as we do not know when the user will start playing.  The idea is to have the bin/input run both a server and a client at the same time. Which can be used to then transmit bidirectional information.

🐛 fix(input): Retry when namespace doesn't exist

---

.scripts/supervisord.conf

Supervisord fails to run as user `netris` no longer exists. So we are renaming all occurrences of old username with new username `nestri`

🐛 fix(server): Replace netris with nestri in supervisord.conf

---

.github/workflows/autolabeller.yml

We are using my personal account key to do autolabelling. This used to work when the project was under my personal, but now it breaks whenever some 3rd party tries to open a PR

🐛 fix(autolabeller): Use `GITHUB_TOKEN` for autolabelling

---

.github/workflows/autolabeler.yml

PR labeler does not work on PR forks, still... I dunno why

🐛 fix(labeler): Use remote config

---

base.Dockerfile

The `gpu-screen-recorder` project switched to using meson instead of a custom build script (see [commit](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=dfa7dc6659755b7a8385aad5003fd80483dd4ffe))
Rather than using the `install.sh` which is now deprecated, I switched to using meson and ninja to build & install.
My text-editor wanted to format the end of the file as well, but that is hopefully no issue :sweat_smile:

🐛 fix(base): Use meson for gpu-screen-recorder

---

.patches/connectcheckskip.patch
.scripts/entrypoint.sh
.scripts/gpu_helpers.sh
base.Dockerfile
server.Dockerfile

In nutshell, this adds support for running Nestri with Intel and AMD GPU's. Both integrated and dedicated.
It took a few days to find a trick for having output without dummy plugs or connected displays, but I think I got it. 
`gpu-screen-recorder` requires a custom patch to skip the check for connected displays (as we're using a xrandr workaround which makes them stay "unconnected")
Most likely fixes #68
The NVIDIA sections have been split in their own code branches since there's some NVIDIA specific things I didn't feel approriate to poke more than necessary for the goal of this PR.
Added a script with helper functions related to GPU discovery and gathering some basic info off from them (note: it might be better to declare the helper script arrays outside it's initially run function). …

✨ feat(server): Add Intel/AMD GPU support

---

.patches/devicearg.patch
.scripts/entrypoint.sh
.scripts/gpu_helpers.sh
base.Dockerfile

Adds new `-device` argument for gpu-screen-recorder which allows specifying a GPU to use (by `/dev/dri/cardN` path)
This fixes an issue with multi-gpu systems when device such as `/dev/dri/card1` is passed through but gpu-screen-recorder will still try to access `/dev/dri/card0` for capturing and failing.
Added relevant bits to `gpu_helpers.sh` to find the card path - I assume all modern modesetting drivers will have a `/drm/` path that tells the card number. If not, the script will fall back to gpu-screen-recorder's own method of finding the card.
Edit: Forgot to mention patches are now copied to /tmp/ rather than /etc/

🐛 fix(base): Device selection patch for gpu-screen-recorder

---

Containerfile.cachyos
packages/server/src/args.rs
packages/server/src/main.rs

Adds a functional NESTRI_PARAMS env variable to container image, allowing usage like:
```docker run -e NESTRI_PARAMS='--no-audio=true --verbose=true'```
Also adds a no-audio option to help debug stream issues.
Also also, changes the container builder portion to use the actual main nestri repo.

🐛 fix: Container parameter passing, option to disable audio for debugging

---

apps/www/package.json
apps/www/src/routes/play/[id]/index.tsx
packages/input/src/keyboard.ts
packages/input/src/latency.ts
packages/input/src/messages.ts
packages/input/src/mouse.ts
packages/input/src/webrtc-stream.ts
packages/relay/internal/datachannel.go
packages/relay/internal/egress.go
packages/relay/internal/flags.go
packages/relay/internal/latency.go
packages/relay/internal/messages.go
packages/server/src/args.rs
packages/server/src/latency.rs
packages/server/src/main.rs
packages/server/src/messages.rs
packages/server/src/room.rs
packages/server/src/websocket.rs

Add latency trackers, tidy things into separate files, improve code behaviour all around but especially in `nestri-server`, removal of buffering and usage of mutex locking allows to push 120FPS easily again.
Time to see if DOOM is now playable with the hugely increased responsiveness..

feat: Tidy things and improve nestri-server code behaviour

---

containers/runner.Containerfile

CachyOS v3 fails to run pacman while on Amazon Linux 2... causing issues with running our hosted version on ECS
Exact errors:
```bash
[root@2b6cbba9d746 /]# sudo pacman -Syu vim
error: failed to initialize alpm library:
(root: /, dbpath: /var/lib/pacman/)
could not find or read directory
```

🐜 fix(runner): Fix Pacman failing to install packages on Amazon Linux 2

---

.github/workflows/runner.yml
containers/runner.Containerfile
packages/scripts/entrypoint.sh
packages/scripts/gpu_helpers.sh

Fixes gpu_helpers returning "Non-VGA" devices as GPUs.
I was curious about DeepSeek's so I tried it's hand with this as my head isn't quite up-to-speed yet :sweat_smile:
But yeah it seems less error-prone than previous naive string-approach.

🐜 fix(scripts): Use class codes to check for lspci GPU devices

---

apps/www/src/routes/(public)/index.tsx
packages/ui/src/react/footer.tsx

I am trying to fix a bug where the `Bring your own GPU` landing page feature is broken on iOS

🐜 fix(www): Fix GPU lines on iOS
